### ISSUE TITLE
compute job size erroneous behaviour

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/insilico-server#7]
## Issue
When asking for job to compute with the `job_size` keyword, like:
```yml
...
command: mock_workflow
job_size: small
....
```

The server always report back the same jobs even though the smallest jobs may have been already computed
